version: 1
services:
  - name: web
    buildCommand: "pip install -r requirements.txt"
    postBuild: "cd core && python manage.py loaddata fixtures/*.json"
    startCommand: "uwsgi --http :8080 --module fusion.wsgi:application"