# Generated by Django 3.2.10 on 2024-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_feedbacks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedbacks',
            field=models.TextField(max_length=400, verbose_name='Feedbacks'),
        ),
    ]
