# Generated by Django 3.2.10 on 2024-02-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_feedbacks_feedbacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacks',
            name='imagem',
            field=models.ImageField(default='/Users/angela/Projetos/fusion/media', upload_to='media/clientes'),
        ),
    ]
