# Generated by Django 3.2.10 on 2024-02-27 16:23

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedbacks_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='imagem',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to='media/clientes', variations={'thumb': {'crop': True, 'height': 480, 'width': 480}}, verbose_name='Imagem'),
        ),
    ]
