# Generated by Django 3.2.10 on 2024-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_feedbacks_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='icone',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrela_1',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela prenchida'), ('lni-star-half', 'Estrela vazia')], default='lni-star-filled', max_length=16, verbose_name='Estrela 1'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrela_2',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela prenchida'), ('lni-star-half', 'Estrela vazia')], default='lni-star-filled', max_length=16, verbose_name='Estrela 2'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrela_3',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela prenchida'), ('lni-star-half', 'Estrela vazia')], default='lni-star-filled', max_length=16, verbose_name='Estrela 3'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrela_4',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela prenchida'), ('lni-star-half', 'Estrela vazia')], default='lni-star-filled', max_length=16, verbose_name='Estrela 4'),
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrela_5',
            field=models.CharField(choices=[('lni-star-filled', 'Estrela prenchida'), ('lni-star-half', 'Estrela vazia')], default='lni-star-filled', max_length=16, verbose_name='Estrela 5'),
        ),
    ]
