# Generated by Django 3.2.10 on 2024-03-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240304_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbacks',
            name='estrela_1',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='estrela_2',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='estrela_3',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='estrela_4',
        ),
        migrations.RemoveField(
            model_name='feedbacks',
            name='estrela_5',
        ),
        migrations.AddField(
            model_name='feedbacks',
            name='estrelas',
            field=models.IntegerField(choices=[(0, 'Nenhuma estrela'), (1, 'Uma estrela'), (2, 'Duas estrelas'), (3, 'Três estrelas'), (4, 'Quatro estrelas'), (5, 'Cinco estrelas')], default=1, verbose_name='Quantidade de Estrelas'),
        ),
    ]
